DataIngestion:
  ZIP_FILENAME : "Artifacts/Dataset.zip"
  UNZIP_DIRECTORY : "Artifacts/Dataset"

DataValidation:
  IMAGES_DATASET_PATH : "Artifacts/Dataset/images"
  ANNOTATIONS_DATASET_PATH : "Artifacts/Dataset/annotations"
  META_DATA_FILE_PATH : "Artifacts/Dataset/Meta-Data.csv"
  TRAIN_DATA_FILE_PATH : "Artifacts/train" 
  VALIDATION_DATA_FILE_PATH : "Artifacts/validation"
  TEST_DATA_FILE_PATH : "Artifacts/test"

DataPreparation:
  TRAIN_META_DATA_FILE_PATH : "Artifacts/train/Meta-Data.csv"
  VALIDATION_META_DATA_FILE_PATH : "Artifacts/validation/Meta-Data.csv"

FeatureExtraction:
  PICKLE_TRAIN_IMAGES_FEATURES_PATH : "Artifacts/train/image_features.pkl"
  PICKLE_TRAIN_BB_FEATURES_PATH : "Artifacts/train/bb_labels.pkl"
  PICKLE_TRAIN_TEXT_SEQUENCES_FEATURES_PATH : "Artifacts/train/text_sequences.pkl"
  PICKLE_VALIDATION_IMAGES_FEATURES_PATH : "Artifacts/validation/image_features.pkl"
  PICKLE_VALIDATION_BB_FEATURES_PATH : "Artifacts/validation/bb_labels.pkl"
  PICKLE_VALIDATION_TEXT_SEQUENCES_FEATURES_PATH : "Artifacts/validation/text_sequences.pkl"
  PICKLE_TOKENIZER_PATH : "Artifacts/tokenizer.pkl"
  PICKLE_STANDARD_SCALER_PATH : "Artifacts/StandardScaler.pkl"


ModelArchitecture:
  SAVE_MODEL_PATH: "Artifacts/VIOV_Model.pkl"

ModelCallbacks:
  BEST_MODEL_PATH: "Artifacts/Best_model.h5"
  PICKLE_MODEL_CALLBACKS: "Artifacts/callbacks.pkl"

ModelTraining:
  SAVE_MODEL_PATH: "Artifacts/VIOV_Model.pkl"
  PICKLE_MODEL_CALLBACKS: "Artifacts/callbacks.pkl"
  BEST_MODEL_PATH: "Artifacts/Best_model.h5"
  MODEL_HISTORY_PICKLE : "Artifacts/Model_history.pkl"
  PICKLE_TRAIN_IMAGES_FEATURES_PATH : "Artifacts/train/image_features.pkl"
  PICKLE_TRAIN_BB_FEATURES_PATH : "Artifacts/train/bb_labels.pkl"
  PICKLE_TRAIN_TEXT_SEQUENCES_FEATURES_PATH : "Artifacts/train/text_sequences.pkl"
  PICKLE_VALIDATION_IMAGES_FEATURES_PATH : "Artifacts/validation/image_features.pkl"
  PICKLE_VALIDATION_BB_FEATURES_PATH : "Artifacts/validation/bb_labels.pkl"
  PICKLE_VALIDATION_TEXT_SEQUENCES_FEATURES_PATH : "Artifacts/validation/text_sequences.pkl" 

  ModelTesting:
    BEST_MODEL_PATH : "Artifacts/Best_model.h5"
    PICKLE_TOKENIZER_PATH : "Artifacts/tokenizer.pkl"
    PICKLE_STANDARD_SCALER_PATH : "Artifacts/StandardScaler.pkl"
    SAVE_RESULTS_PATH : "Artifacts/Results"
