ModelArchitecture:
  FEATURE_SIZE: 512
  TEXT_SEQUENCE_INPUT_LENGTH: 100
  EMBEDDING_INPUT_DIMS : 3000
  EMBEDDING_OUTPUT_DIMS : 2500
  LEARNING_RATE: 0.0001
  LOSS : "mse"  

ModelCallbacks:
  SAVE_BEST_ONLY : True  