FeatureExtraction:
  SET_TYPE: {"train":"train","validation":"validation"}

ModelArchitecture:
  FEATURE_SIZE: 512
  TEXT_SEQUENCE_INPUT_LENGTH: 100
  EMBEDDING_INPUT_DIMS : 3000
  EMBEDDING_OUTPUT_DIMS : 2500
  LEARNING_RATE: 0.0001
  LOSS : "mse"  

ModelCallbacks:
  SAVE_BEST_ONLY : True  

ModelTraining:
  EPOCHS: 1
  BATCH_SIZE : 10
  VALIDATION_BATCH_SIZE: 10 

ModelTesting:
  SOURCE : "Artifacts/test/videos/pexels_videos_2108672 (720p).mp4"
  TEXT : "A red light above the road"
